# ######################################################################################################################
# Kinesis Firehose Stream to Amazon S3
# Version: 1.0
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Creates a Kinesis Data Stream with the desired shard count in provisioned mode.
#
# ##############################################################################################################
Parameters:
  ShardCount:
    Description: "Number of shards to provision in your Kinesis Data Stream"
    Type: Number
    Default: 1
  RetentionPeriod:
    Description: "Retention period in hours"
    Type: Number
    Default: 24
Resources:
  KinesisDataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      RetentionPeriodHours: !Ref RetentionPeriod
      ShardCount: !Ref ShardCount
      StreamModeDetails:
        StreamMode: PROVISIONED
      Tags:
        - Key: Environment
          Value: !Sub ${AWS::StackName}