# ######################################################################################################################
# EMR Studio Service catalog portfolio setup
# Version: 1.0
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Creates portfolio and product self-serve the EMR templates within EMR Studio
#
# Remember that service catalog product names cannot have spaces otherwise workspace
# deployment in EMR Studio will fail.
# #######################################################################################################################
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DefaultSSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of the key pair to use for default with EMR clusters."
Resources:
  ServiceCatalogPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      Description: "EMR Studio Sample Templates"
      DisplayName: !Sub ${AWS::StackName}-portfolio
      ProviderName: !Sub ${AWS::StackName}-provider
  ServiceCatalogLaunchConstrainRole:
    Type: AWS::IAM::Role
    Properties:
      Description: "Allow service catalog actions on EMR, Cloudformation and Service Actions"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: servicecatalog.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEMRFullAccessPolicy_v2
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      Policies:
        - PolicyName: !Sub ${AWS::StackName}_EMRLaunchConstrainRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Sid: DeployEMR
                Action:
                  - "s3:GetObject"
                Resource: "*"
              - Effect: Allow
                Sid: MacroLambda
                Action:
                  - "lambda:InvokeFunction"
                Resource: !ImportValue emr-capacity-macro-lambda
              - Effect: Allow
                Action:
                  - "iam:PassRole"
                Resource:
                  - !ImportValue EMRServiceRole
                  - !ImportValue EMREC2Role
  EMRTemplateProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Description: "Sample EMR Template to be deployed in EMR Studio"
      Distributor: !Sub ${AWS::StackName}_provider
      Name: !Sub ${AWS::StackName}
      Owner: "aws-samples"
      ProvisioningArtifactParameters:
        - Info:
            LoadTemplateFromURL: !Sub "https://s3.${AWS::Region}.amazonaws.com/emrstudio.sample.templates/templates/emr-cluster-template-for-service-catalog.yaml"
          Name: "EMRTemplateV2024.3.6"
      SupportDescription: "Sample Amazon EMR cluster template for self service deployment by data engineering and data science organizations."
  EMRTemplateProductAssociation1:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref ServiceCatalogPortfolio
      ProductId: !Ref EMRTemplateProduct
  ServiceCatalogRoleConstrain1:
    Type: AWS::ServiceCatalog::LaunchRoleConstraint
    Properties:
      Description: "Use Cloudformation, EMR and ServiceCatalog"
      PortfolioId: !Ref ServiceCatalogPortfolio
      ProductId: !Ref EMRTemplateProduct
      RoleArn: !GetAtt ServiceCatalogLaunchConstrainRole.Arn
  PortfolioPermissions:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId: !Ref ServiceCatalogPortfolio
      PrincipalARN: !ImportValue EMRStudioAdminRole
      PrincipalType: IAM
Outputs:
  EMRSSHKey:
    Description: 'Default key pair name for EMR cluster'
    Value: !Ref DefaultSSHKey
    Export:
      Name: EMRDefaultSSHKey